import * as Ant from "./ant.js";
import * as HRS from "./heart-rate-sensors.js";
import * as SSD from "./stride-speed-distance-sensors.js";
import * as SC from "./speed-cadence-sensors.js";
import * as S from "./speed-sensors.js";
import * as C from "./cadence-sensors.js";
import * as BP from "./bicycle-power-sensors.js";
import * as FE from "./fitness-equipment-sensors.js";
import * as MO from "./muscle-oxygen-sensors.js";
import * as E from "./environment-sensors.js";

export const GarminStick2 = Ant.GarminStick2;
export const GarminStick3 = Ant.GarminStick3;
export const HeartRateSensor = HRS.HeartRateSensor;
export const HeartRateScanner = HRS.HeartRateScanner;
export const StrideSpeedDistanceSensor = SSD.StrideSpeedDistanceSensor;
export const StrideSpeedDistanceScanner = SSD.StrideSpeedDistanceScanner;
export const SpeedCadenceSensor = SC.SpeedCadenceSensor;
export const SpeedCadenceScanner = SC.SpeedCadenceScanner;
export const SpeedSensor = S.SpeedSensor;
export const SpeedScanner = S.SpeedScanner;
export const CadenceSensor = C.CadenceSensor;
export const CadenceScanner = C.CadenceScanner;
export const BicyclePowerSensor = BP.BicyclePowerSensor;
export const BicyclePowerScanner = BP.BicyclePowerScanner;
export const FitnessEquipmentSensor = FE.FitnessEquipmentSensor;
export const FitnessEquipmentScanner = FE.FitnessEquipmentScanner;
export const MuscleOxygenSensor = MO.MuscleOxygenSensor;
export const MuscleOxygenScanner = MO.MuscleOxygenScanner;
export const EnvironmentSensor = E.EnvironmentSensor;
export const EnvironmentScanner = E.EnvironmentScanner;
