import * as GarminStick2Js from "./core/GarminStick2.js";
import * as GarminStick3Js from "./core/GarminStick3.js";
import * as HeartRateScannerJs from "./sensors/heartRate/HeartRateScanner.js";
import * as HeartRateSensorJs from "./sensors/heartRate/HeartRateSensor.js";
import * as StrideSpeedDistanceScannerJs from "./sensors/strideSpeedDistance/StrideSpeedDistanceScanner.js";
import * as StrideSpeedDistanceSensorJs from "./sensors/strideSpeedDistance/StrideSpeedDistanceSensor.js";
import * as SpeedCadenceScannerJs from "./sensors/speedCadence/SpeedCadenceScanner.js";
import * as SpeedCadenceSensorJs from "./sensors/speedCadence/SpeedCadenceSensor.js";
import * as SpeedScannerJs from "./sensors/speed/SpeedScanner.js";
import * as SpeedSensorJs from "./sensors/speed/SpeedSensor.js";
import * as CadenceScannerJs from "./sensors/cadence/CadenceScanner.js";
import * as CadenceSensorJs from "./sensors/cadence/CadenceSensor.js";
import * as BicyclePowerScannerJs from "./sensors/bicyclePower/BicyclePowerScanner.js";
import * as BicyclePowerSensorJs from "./sensors/bicyclePower/BicyclePowerSensor.js";
import * as FitnessEquipmentScannerJs from "./sensors/fitnessEquipment/FitnessEquipmentScanner.js";
import * as FitnessEquipmentSensorJs from "./sensors/fitnessEquipment/FitnessEquipmentSensor.js";
import * as MuscleOxygenScannerJs from "./sensors/muscleOxygen/MuscleOxygenScanner.js";
import * as MuscleOxygenSensorJs from "./sensors/muscleOxygen/MuscleOxygenSensor.js";
import * as EnvironmentScannerJs from "./sensors/environment/EnvironmentScanner.js";
import * as EnvironmentSensorJs from "./sensors/environment/EnvironmentSensor.js";

export const GarminStick2 = GarminStick2Js.GarminStick2;
export const GarminStick3 = GarminStick3Js.GarminStick3;
export const HeartRateSensor = HeartRateSensorJs.HeartRateSensor;
export const HeartRateScanner = HeartRateScannerJs.HeartRateScanner;
export const StrideSpeedDistanceSensor = StrideSpeedDistanceSensorJs.StrideSpeedDistanceSensor;
export const StrideSpeedDistanceScanner = StrideSpeedDistanceScannerJs.StrideSpeedDistanceScanner;
export const SpeedCadenceSensor = SpeedCadenceSensorJs.SpeedCadenceSensor;
export const SpeedCadenceScanner = SpeedCadenceScannerJs.SpeedCadenceScanner;
export const SpeedSensor = SpeedSensorJs.SpeedSensor;
export const SpeedScanner = SpeedScannerJs.SpeedScanner;
export const CadenceSensor = CadenceSensorJs.CadenceSensor;
export const CadenceScanner = CadenceScannerJs.CadenceScanner;
export const BicyclePowerSensor = BicyclePowerSensorJs.BicyclePowerSensor;
export const BicyclePowerScanner = BicyclePowerScannerJs.BicyclePowerScanner;
export const FitnessEquipmentSensor = FitnessEquipmentSensorJs.FitnessEquipmentSensor;
export const FitnessEquipmentScanner = FitnessEquipmentScannerJs.FitnessEquipmentScanner;
export const MuscleOxygenSensor = MuscleOxygenSensorJs.MuscleOxygenSensor;
export const MuscleOxygenScanner = MuscleOxygenScannerJs.MuscleOxygenScanner;
export const EnvironmentSensor = EnvironmentSensorJs.EnvironmentSensor;
export const EnvironmentScanner = EnvironmentScannerJs.EnvironmentScanner;
